version: '2.1'

services:
  client:
    image: client
    container_name: client
    build: ./client
    volumes:
      - ./client/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '3000:80'
    depends_on:
      - rest-api

  processor:
    image: processor
    container_name: processor
    build: ./processor
    volumes:
      - ./processor:/processor
      - /processor/node_modules
    depends_on:
      - validator
    environment:
      - VALIDATOR_URL=tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator
    expose:
      - 4004
      - 8800
    ports:
      - '4004:4004'
      - '8800:8800'
    # Starts a validator with PoET consensus
    # Replace tcp://docker.for.mac.localhost:8800 with your IP
    entrypoint: "bash -c \"\
        sawadm keygen --force && \
        sawset genesis \
          -k /etc/sawtooth/keys/validator.priv \
          -o config-genesis.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
          sawtooth.consensus.algorithm=poet \
          sawtooth.poet.report_public_key_pem=\
          \\\"$$(cat /etc/sawtooth/simulator_rk_pub.pem)\\\" \
          sawtooth.poet.valid_enclave_measurements=$$(poet enclave measurement) \
          sawtooth.poet.valid_enclave_basenames=$$(poet enclave basename) \
          -o config.batch && \
        poet registration create -k /etc/sawtooth/keys/validator.priv -o poet.batch && \
        sawset proposal create \
          -k /etc/sawtooth/keys/validator.priv \
             sawtooth.poet.target_wait_time=5 \
             sawtooth.poet.initial_wait_time=25 \
             sawtooth.publisher.max_batches_per_block=100 \
          -o poet-settings.batch && \
        sawadm genesis \
          config-genesis.batch config.batch poet.batch poet-settings.batch && \
        sawtooth-validator -v \
          --bind network:tcp://eth0:8800 \
          --bind component:tcp://eth0:4004 \
          --peering dynamic \
          --endpoint tcp://docker.for.mac.localhost:8800 \
          --scheduler serial \
          --network trust \
          --minimum-peer-connectivity 1
    \""
    # Use the following code if not the first validator.
    # Once again, replace docker.for.mac.localhost with the appropriate URL:
    # entrypoint: |
    #   bash -c "
    #     if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
    #       sawadm keygen &&
    #       sawtooth keygen my_key
    #     fi;
    #     sawtooth-validator -v \
    #       --bind component:tcp://eth0:4004 \
    #       --bind network:tcp://eth0:8800 \
    #       --endpoint tcp://docker.for.mac.localhost:8800 \
    #       --peering dynamic \
    #       --seeds tcp://docker.for.mac.localhost:8800 \
    #       --minimum-peer-connectivity 1
    #   "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -v -C tcp://validator:4004

  poet-validator-registry-tp:
    image: hyperledger/sawtooth-poet-validator-registry-tp:1.0
    container_name: sawtooth-poet-validator-registry-tp
    expose:
      - 4004
    command: poet-validator-registry-tp -C tcp://validator:4004
    environment:
      PYTHONPATH: /project/sawtooth-core/consensus/poet/common
    stop_signal: SIGKILL

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -v
        --connect tcp://validator:4004
        --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: shell
    depends_on:
      - rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        tail -f /dev/null
      "
